version: '3'

services:
  db:
    image: postgres:9.6.17
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'

volumes:
  postgresql:
    driver: local
